// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../src/tables/JobBoardTable.sol";
import "../src/tables/MarketplaceTable.sol";

// Migrates existing data from the old JobBoardTable and MarketplaceTable
// into the newly deployed contracts that support the operator allowlist.
//
// Usage:
//   forge script script/MigrateTableData.s.sol \
//     --rpc-url https://arb1.arbitrum.io/rpc \
//     --broadcast --via-ir --optimize --optimizer-runs 200
//
// After migration, update ui/const/config.ts:
//   JOBS_TABLE_ADDRESSES arbitrum -> 0x2113341dEc8a0fB9883Ad494C589d5cdefDDBc1b
//   MARKETPLACE_TABLE_ADDRESSES arbitrum -> 0xF0AeE0c837943fa1919538B12b5d9AE11C5EED05

contract MigrateTableData is Script {
    address constant NEW_JOB_BOARD    = 0x2113341dEc8a0fB9883Ad494C589d5cdefDDBc1b;
    address constant NEW_MARKETPLACE  = 0xF0AeE0c837943fa1919538B12b5d9AE11C5EED05;

    function run() external {
        uint256 deployerPk = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPk);

        JobBoardTable jobs = JobBoardTable(NEW_JOB_BOARD);
        MarketplaceTable market = MarketplaceTable(NEW_MARKETPLACE);

        // ── Jobs (11 records from JOBBOARD_42161_115) ────────────────────────
        jobs.insertIntoTable("Full Stack Smart Contract Engineer", "We're looking for full-stack engineers that are proficient with Solidity and smart contracts, and have some familiarity with DAOs. Ideal candidates have strong relevant professional or project work.\n\nYou would work closely with the founder and tackle new problems in DAOs, innovating on the frontiers of DAO governance, incentives, and finance.\n\nSend an email to pablo@moondao.com with your resume and why you would be an amazing fit for supporting MoonDAO.", 0, "", "", 1830240000, 1773432256, "mailto:pablo@moondao.com");
        jobs.insertIntoTable("2025 Fellowship Program- Applications Open", "Applications for our 2025 fellowship cohort are now open! Are you passionate about creating a sustainable and peaceful lunar future? Join our global fellowship program and contribute to groundbreaking research! As an Open Lunar fellow, you'll develop innovative lunar research projects while collaborating with leading experts in the space community. We welcome diverse backgrounds and unconventional thinkers. Learn more!", 9, "", "", 1733983200, 1731449654, "https://www.openlunar.org/blog/2025-fellowship");
        jobs.insertIntoTable("Director of Operations - Open Lunar Foundation", "We are looking for a Director of Operations who is passionate about our mission and has a talent for strategic planning, program management, and operational leadership. This role is crucial to enhancing the efficiency of our operations and ensuring the successful execution of our initiatives. As the Director of Operations, you will be the backbone of our organization, managing the day-to-day execution of programs, financial oversight, legal compliance, and communications. Learn more!", 9, "", "", 1733983200, 1731449654, "https://www.openlunar.org/blog/doo-applications");
        jobs.insertIntoTable("Launch the LifeShip DAO", "LifeShip is building towards the launch of a DAO. Get in touch if you want to be one of the early members. We don't have paid positions at the moment. Compensation would be in tokens in the launch. LifeShip is a space society to preserve Earth and spread life to the stars. LifeShip's initial missions are monuments on the Moon with a backup of Earth. The vision builds towards a temple on the Moon and communities across Earth and space.", 2, "", "", 1733983200, 1731449654, "mailto:connect@lifeship.com");
        jobs.insertIntoTable("BD / Sales / Affiliates at LifeShip", "LifeShip is looking for passionate individuals to drive business development, product sales, and commission-based B2B partnerships for our space-as-a-service offerings. LifeShip's is launching a series of monuments to the Moon as backups of Earths biodiversity, culture, and legacy. LifeShip has consumer products for people to send DNA, art, ashes, and more to the Moon. LifeShip has B2B partnerships with organizations wanting to send content to the Moon. Compensation in commission and equity.", 2, "", "", 1733983200, 1731449654, "mailto:jobs@lifeship.com");
        jobs.insertIntoTable("CMO/Shiller", "We are looking for a person to shill LunCo & Decentralized Space Exploration on the Internet: If you are: - want to contribute to Lunar Exploration - have exp in marketing, particularly shilling on X Spaces - Web3-native or web3-ready will to go full on crypto Jump on our Discord to say hi, maybe we could build something cool together", 12, "", "", 1748624400, 1733101252, "https://discord.gg/A6U3GdvQum");
        jobs.insertIntoTable("Co-Executive Director, VP of Industry Integration/Executive Dir.", "We are hiring an executive role which will either become the Executive Director, or the Co-Executive Director. In this role, youll cultivate industry relationships, oversee innovative R&D projects, and lead significant fundraising efforts. You must have significant fundraising experience to succeed in this role.\n\nRead more here: https://www.openlunar.org/blog/hiring-in-2025\n", 9, "", "", 1738292400, 1736513444, "https://docs.google.com/forms/d/e/1FAIpQLSeCUhoHtIXkEjp8orc6pMRamEpehkqnirnq8Ss6VAaeRzfl1g/viewform");
        jobs.insertIntoTable("Director of Operations, COO / Operations and Programs Manager", "We are hiring for an operations lead who will either become the COO level ops leader, or an Ops manager role. The difference here will be determined by seniority of candidates, and by the balance of needs met across other team mates. Operating the Open Lunar Foundation requires 501c3 experience regarding finance, compliance and legal standing, as well as a passion for Asana ;) and running meetings. \n\nRead more here: https://www.openlunar.org/blog/hiring-in-2025", 9, "", "", 1738292400, 1736513541, "https://docs.google.com/forms/d/e/1FAIpQLSc1YB8ol3cVXnJPjIUUzY10GkwWhK89g9CVc2Hy6DojwYt9dg/viewf");
        jobs.insertIntoTable("Director of Operations, COO / Operations and Programs Manager", "We are hiring for an operations lead who will either become the COO level ops leader, or an Ops manager role. The difference here will be determined by seniority of candidates, and by the balance of needs met across other team mates. Operating the Open Lunar Foundation requires 501c3 experience regarding finance, compliance and legal standing, as well as a passion for Asana ;) and running meetings. \n\nRead more here: https://www.openlunar.org/blog/hiring-in-2025", 9, "", "", 1738292400, 1736513834, "https://docs.google.com/forms/d/e/1FAIpQLSc1YB8ol3cVXnJPjIUUzY10GkwWhK89g9CVc2Hy6DojwYt9dg/viewf");
        jobs.insertIntoTable("Research Fellow ", "Time Commitment & Compensation\nCommitment: Up to 8 hours per week for 58 months (starting in January), depending on scope. \n\nCompensation: USD $35/hour\n\nLocation: Flexible and remote (Open Lunar operates globally; meetings often scheduled in Eastern Time Zone)\n\nWhat Fellows Do\nResearch & Analysis\nInvestigate emerging ideas for peaceful lunar development\n\nDraft background papers, reports, and articles\n\nDevelop annotated bibliographies and reading lists\n\nSupport research organization and synthesis\n\nCollaboration\nParticipate in weekly fellowship calls with peers and staff\n\nPresent findings at research showcases and conferences\n\nEngage with diverse stakeholders and incorporate feedback\n\nDeliverables\nClear, concise outputs accessible to broad audiences\n\nProvocative insights that drive new thinking in lunar governance\n\nFinal research presented as a published report, white paper, and community showcase\n\n\nWhat You'll Gain\nLead a research project with an or", 9, "", "", 1760065200, 1757336731, "https://www.openlunar.org/research-fellowship");
        jobs.insertIntoTable("Overview Effect Mission Ambassadors", "Join our initiative to send the author of The Overview Effect, Frank White, to space. We are seeking dedicated volunteer Mission Ambassadors to help us raise the funds required to secure two commercial spaceflight tickets. As an ambassador, you will utilize our comprehensive media kit to seek out donors, share on social media, and amplify the campaign. Keep in mind that your primary objective is to mobilize your network to back the overall mission, while also asking contributors to vote for you and back your candidacy for the second seat. To apply and get started immediately, access the media kit below.", 20, "", "", 1777266000, 1774103036, "https://moondao.com/overview-media");

        // ── Marketplace (13 records from MARKETPLACE_42161_116) ──────────────
        market.insertIntoTable("MoonDAO Logo T-Shirt", "Show your pride in the Internet's Space Program with this exclusive MoonDAO logo t-shirt. Perfect for space enthusiasts and DAO pioneers alike, this shirt represents the future of decentralized space exploration. Join the movement that's taking humanity beyond Earth--one mission at a time!", "ipfs://QmTuBQJNYAdBZNTf8oXxskYSBYRACFah9Jpkf2KeYyG1BH", 0, "20", "USDC", 0, 0, 1736345180, "", "", "true");
        market.insertIntoTable("DAO Consulting", "Interested in launching your own DAO? Want help with the process of developing, funding, and operating a DAO? Book a 1 hour consultation with the MoonDAO core team to support your needs.", "ipfs://QmWUgJNsHiSNKiGFnu7iXX99aNXAampBqLgxoerjnCDNQc", 0, "0.05", "ETH", 0, 0, 1731449654, "", "", "false");
        market.insertIntoTable("LifeShip: Send your DNA to the Moon", "Realize your dreams of going to space and leave a legacy in the cosmos! With a LifeShip DNA kit, youll become part of a pioneering mission to expand humanity to the stars. Preserve your unique DNA on the Moon. Launch on a SpaceX rocket and watch live for the lunar landing. Youll receive a DNA collection kit, mission patch, and a digital certificate to commemorate your journey. Join a backup of Earth and send your DNA to the Moon.", "ipfs://QmSWS2rLMpRvoNyZfTeGyAMHCoWxwGvZ97bwSVDVdpqQ8f", 2, "99", "USDC", 0, 0, 1731449654, "", "", "true");
        market.insertIntoTable("Send a custom plaque to the Moon with your Art", "Send your photo or artwork to the Moon with LifeShip, creating a unique and lasting lunar legacy! Your art will be UV printed in full color on a custom 1x1-inch aluminum layer and permanently preserved on the lunar surface. You'll receive two copies to keep on Earth, while one is sent to the Moon, allowing your vision to inspire future generations. Optional archival-grade Nickel NanoFiche or Ceramic for the highest resolution and durability are an added cost. Share your art with the universe!", "ipfs://QmY2iMh83VHGPCG6PDbAweZdYG7yYwTDFPkupH8bjyo6ZL", 2, "4200", "USDC", 0, 0, 1731449654, "", "", "true");
        market.insertIntoTable("Cultura Series V1-  Luxury T-Shirt", "Symbiont Labs believes that our relationship with technology should be expressed through multiple mediums beyond cybernetic implants. Here in fabric our substrate canvas becomes an invitation into deeper worlds of meaning transcending physical form. The Cultura Series is inspired by a unique fusion of pre-columbian futurism with reimagined cyberpunk twist in a collaboration with Honduran artisan and muralist Luis Vasquez.", "ipfs://QmNzKyu9g5xoPdhp122GzEXcvNtTXAWUU3ZXK6wLF1SSDM", 11, "30", "USDC", 0, 0, 1732310388, "", "", "true");
        market.insertIntoTable("Cybernetics Engineering / Prototyping  Consultation", "Are you interested in designing or commissioning a custom cybernetic implant?  Do you want expert help with the process of developing, funding, and operating a subdermal device? Book a 1 hour video consultation  and up an hour of background research with the Symbiont Labs team to support your needs. We're open to any project and budget but it all starts with a call.", "ipfs://QmVsv1UZWq8sbBa5LL8swaSBM8QvPSivtuweXhufutDyKW", 11, "199", "USDC", 0, 0, 1733439843, "", "", "false");
        market.insertIntoTable("Mission Patch Design Service", "Celebrate your space mission with a custom mission patch!\n\n5 sketches, 2 revisions\nDelivery of color and monochrome versions as .svg vector, png, and jpg, with recommendations for production.\n\nSee more examples at: graphicdesignanna.myportfolio.com", "ipfs://Qmf9xg7XmoGUGdoynsPPjy5Yfp499J9AsRvxGcVsf6drBo", 14, "0.15", "ETH", 0, 0, 1738448845, "", "", "false");
        market.insertIntoTable("Mission Painting - Fine Art on Canvas", "Commemorate your mission with a hand-painted acrylic painting on canvas.\n\nArchival finish. \nPrice based on 8x10 in canvas, shipping to North America\n\nContact graphicdesignanna@gmail.com to discuss.", "ipfs://QmS3ehAF1C8GP65XFw1Srds7XwThsNESXdbYyiNqKxavtv", 14, "0.040", "ETH", 0, 0, 1738616970, "", "", "true");
        market.insertIntoTable("ASRI Annual Membership - Standard", "Support the Advanced SpaceLife Research Institute and our research on human reproduction and sexuality factors in space by subscribing as an official ASRI network member! Annual Standard Membership Subscription includes: (1) ASRI Monthly Newsletter  stay up to date with on-going research efforts, events, conference presentations and key individuals involved in the fascinating study of sex in space! (2) Monthly discount codes for ASRI Online Store  new ASRI merchandise items added monthly! (3) Email updates/reminders regarding ASRI developments and upcoming member events  stay ahead of the crowd! (4) Access to members-only ASRI website portal  meet and network with other supporters, build your ASRI profile and community! (5) Access to member-exclusive ASRI social media content! *By purchasing this membership you agree to abide by ASRIs organizational Terms & Conditions of Service, Privacy Policy, and Subscription Member Code of Conduct as published, updated and maintained on our official website. ", "ipfs://QmUeRqRsSSTeETZS2hvLkRggwknhtwmo5sSsnpKFZ3PJBG", 16, "99", "USDC", 0, 0, 1748242291, "", "", "false");
        market.insertIntoTable("Ticket to New Worlds & Space Cowboy Ball | Oct 24-25, 2025 (ETH)", "IT'S BACK!\n\nThe EarthLight Foundation is back in Houston this October.  Join us October 24-25 at Space Center Houston for New Worlds, \"the TED Talks of Space\", and the Space Cowboy Ball, \"A Costume Party on the Moon\".\n\nCheck out the line-up and details at www.newworlds.org.  The MoonDAO community showed up in force last year, and we can't wait to see you all again! (Pablo danced, we saw it with our own eyes.)", "ipfs://QmWLgoGz9VzpDX35cRyYx9Fbet2n6K2xQaAu9EVVtUB49u", 1, ".24", "ETH", 1751342400, 1754020800, 1751335284, "", "", "false");
        market.insertIntoTable("Ticket to New Worlds & Space Cowboy Ball | Oct 24-25, 2025 (USDC)", "IT'S BACK!\n\nThe EarthLight Foundation is back in Houston this October.  Join us October 24-25 at Space Center Houston for New Worlds, \"the TED Talks of Space\", and the Space Cowboy Ball, \"A Costume Party on the Moon\".\n\nCheck out the line-up and details at www.newworlds.org.  The MoonDAO community showed up in force last year, and we can't wait to see you all again! (Pablo danced, we saw it with our own eyes.)", "ipfs://QmWLgoGz9VzpDX35cRyYx9Fbet2n6K2xQaAu9EVVtUB49u", 1, "600", "USDC", 1751342400, 1754020800, 1751335418, "", "", "false");
        market.insertIntoTable("Tickets to New Worlds & Space Cowboy Ball | Oct 24-25, 2025 (MOONEY)", "IT'S BACK!\n\nThe EarthLight Foundation is back in Houston this October.  Join us October 24-25 at Space Center Houston for New Worlds, \"the TED Talks of Space\", and the Space Cowboy Ball, \"A Costume Party on the Moon\".\n\nCheck out the line-up and details at www.newworlds.org.  The MoonDAO community showed up in force last year, and we can't wait to see you all again! (Pablo danced, we saw it with our own eyes.)", "ipfs://QmWLgoGz9VzpDX35cRyYx9Fbet2n6K2xQaAu9EVVtUB49u", 1, "2000000", "MOONEY", 1751342400, 1754020800, 1751335806, "", "", "false");
        market.insertIntoTable("SpaceKind16 Training- Wed Sept 17, 5pm PT - Wed Nov 5, 2025", "Join Loretta Hidalgo Whitesides on an 8-week Hero's Journey to help you take on the next level of your life. Level up your confidence, peace, teamwork, relationships, and joy. Be the person you have always wanted to be. It doesn't start when you get to space, it starts right here. Greatness doesn't come from accomplishment alone, come learn the art of having a great life and your future will be magical where ever the universe takes you. \n\nRegistrations close Wednesday Sept 17, 12 noon Pacific so I have time to get you the zoom link before class starts at 5pm Pacific!\n\nZoom meet-ups run 5:00-6:15 pm Pacific every Wednesday. We will read \"The New Right Stuff: Using Space to Bring out the Best in You\" and have challenges to work on between sessions. \n\nGo to www.spacekind.org for a full course description", "ipfs://QmU9QfGPdDk6hAsJES53WTVLKvJa4f2DUMH2KHmZ1XtCML", 19, ".11", "ETH", 0, 0, 1757904583, "", "", "false");

        vm.stopBroadcast();

        console.log("Migration complete.");
        console.log("Now update ui/const/config.ts:");
        console.log("  JOBS_TABLE_ADDRESSES arbitrum -> ", NEW_JOB_BOARD);
        console.log("  MARKETPLACE_TABLE_ADDRESSES arbitrum -> ", NEW_MARKETPLACE);
    }
}
