[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/"},
    { access = "read", path = "../contracts/deployments/"}
]
evm_version = "cancun"
version = "0.8.26"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
