import { cleanSummaryContent, getPreviewText } from '@/lib/townhall/utils'

describe('cleanSummaryContent', () => {
  it('removes style tags and their content', () => {
    const html = '<style>body { color: red; }</style><p>Content here</p>'
    const result = cleanSummaryContent(html)
    
    expect(result).to.not.include('style')
    expect(result).to.not.include('color: red')
    expect(result).to.include('Content here')
  })

  it('removes script tags and their content', () => {
    const html = '<script>alert("test");</script><p>Content here</p>'
    const result = cleanSummaryContent(html)
    
    expect(result).to.not.include('script')
    expect(result).to.not.include('alert')
    expect(result).to.include('Content here')
  })

  it('removes h1 tags', () => {
    const html = '<h1>Town Hall Summary</h1><p>Content here</p>'
    const result = cleanSummaryContent(html)
    
    expect(result).to.not.include('h1')
    expect(result).to.not.include('Town Hall Summary')
    expect(result).to.include('Content here')
  })

  it('removes auto-generation footer', () => {
    const html = '<p>Content here</p><p><em>This summary was automatically generated by AI.</em></p>'
    const result = cleanSummaryContent(html)
    
    expect(result).to.include('Content here')
    expect(result).to.not.include('automatically generated')
  })

  it('removes trailing hr tags', () => {
    const html = '<p>Content here</p><hr />'
    const result = cleanSummaryContent(html)
    
    expect(result).to.include('Content here')
    expect(result).to.not.match(/<hr.*>$/)
  })

  it('handles empty content', () => {
    const result = cleanSummaryContent('')
    
    expect(result).to.equal('')
  })

  it('trims whitespace', () => {
    const html = '   <p>Content here</p>   '
    const result = cleanSummaryContent(html)
    
    expect(result).to.equal('<p>Content here</p>')
  })

  it('preserves valid HTML structure', () => {
    const html = '<h2>Section</h2><p>Paragraph 1</p><ul><li>Item 1</li></ul>'
    const result = cleanSummaryContent(html)
    
    expect(result).to.include('<h2>')
    expect(result).to.include('<p>')
    expect(result).to.include('<ul>')
    expect(result).to.include('<li>')
  })
})

describe('getPreviewText', () => {
  it('returns full text when under max length', () => {
    const text = 'Short text'
    const result = getPreviewText(text, 100)
    
    expect(result).to.equal('Short text')
  })

  it('truncates at word boundary', () => {
    const text = 'This is a very long piece of text that should be truncated'
    const result = getPreviewText(text, 20)
    
    expect(result).to.not.include('truncated')
    expect(result.endsWith('...')).to.be.true
    expect(result.length).to.be.lessThan(24)
  })

  it('adds ellipsis when truncated', () => {
    const text = 'This is a long text that needs to be shortened for preview purposes'
    const result = getPreviewText(text, 30)
    
    expect(result.endsWith('...')).to.be.true
  })

  it('handles empty content', () => {
    const result = getPreviewText('')
    
    expect(result).to.equal('')
  })

  it('removes HTML tags for preview', () => {
    const html = '<p>This is <strong>bold</strong> text</p>'
    const result = getPreviewText(html, 100)
    
    expect(result).to.not.include('<p>')
    expect(result).to.not.include('<strong>')
    expect(result).to.include('This is bold text')
  })

  it('does not cut words in the middle', () => {
    const text = 'This is some text with multiple words'
    const result = getPreviewText(text, 15)
    
    const lastWord = result.replace('...', '').trim().split(' ').pop()
    expect(text).to.include(lastWord || '')
  })

  it('uses default max length of 200 when not specified', () => {
    const longText = 'a'.repeat(300)
    const result = getPreviewText(longText)
    
    expect(result.length).to.be.lessThan(204)
    expect(result.endsWith('...')).to.be.true
  })

  it('trims whitespace from result', () => {
    const text = '   Text with spaces   '
    const result = getPreviewText(text, 100)
    
    expect(result).to.equal('Text with spaces')
  })
})

