name: Deploy Event Changes

on:
  push:
    branches:
      - main
    paths:
      - 'Events/**'
      - '.gitmodules'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.MOONDAO_EVENTS_HANDLER }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        
      - name: 'Configure Docker for Artifact Registry'
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
        
      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy dispatcher-service \
            --source . \
            --platform managed \
            --region us-central1 \
            --set-secrets WORDWARE_API_KEY=wordware-api-key:latest \
            --memory 512Mi \
            --min-instances 1 \
            --max-instances 1 \
            --service-account=758767203349-compute@developer.gserviceaccount.com