steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/townhall-summarizer", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/townhall-summarizer"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "townhall-summarizer"
      - "--image"
      - "gcr.io/$PROJECT_ID/townhall-summarizer"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--timeout"
      - "3600"
      - "--memory"
      - "512Mi"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--allow-unauthenticated"
      - "--set-secrets"
      - "GROQ_API_KEY=groq-api-key:latest,YOUTUBE_API_KEY=youtube-api-key:latest,ALLOWED_YOUTUBE_CHANNEL_ID=allowed-youtube-channel-id:latest,DISCORD_WEBHOOK_URL=discord-webhook-url:latest,/secrets/youtube-cookies.txt=youtube-cookies:latest"
      - "--set-env-vars"
      - "YOUTUBE_COOKIE_FILE=/secrets/youtube-cookies.txt"
