steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dispatcher-service', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dispatcher-service']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dispatcher-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dispatcher-service'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--set-secrets'
      - 'WORDWARE_API_KEY=wordware-api-key:latest'
      - '--memory'
      - '512Mi'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '1'
