[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Exclude subscription-contracts to avoid dependency issues
ignore_compile = ["../subscription-contracts"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
