/**
 * Fetch a YouTube video's caption/subtitle track via the YouTube transcript
 * API (no yt-dlp, no cookies, no bot-detection issues).
 *
 * Uses the `youtube-transcript` package which calls YouTube's public timedtext
 * endpoint directly — works from any IP including GitHub Actions and Cloud Run.
 *
 * Falls back to null if no transcript is available (e.g. auto-captions haven't
 * been generated yet for a very recent live stream). The caller (`getTranscript`)
 * then falls back to the full audio-download path.
 */

import { YoutubeTranscript, TranscriptResponse } from "youtube-transcript";

/**
 * Download the transcript for a YouTube video using the public timedtext API.
 * Returns the plain-text transcript, or null if unavailable.
 */
export async function fetchYouTubeCaptionsTranscript(
  videoId: string
): Promise<{ transcript: string; isAutoGenerated: boolean } | null> {
  // Validate videoId to prevent injection (YouTube IDs are always 11 alphanumeric/-/_ chars)
  if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    console.error(`Invalid videoId format: ${videoId}`);
    return null;
  }

  try {
    console.log(`Fetching transcript for ${videoId} via YouTube API...`);
    const segments: TranscriptResponse[] = await YoutubeTranscript.fetchTranscript(videoId, { lang: "en" });

    if (!segments || segments.length === 0) {
      console.warn(`No transcript segments returned for ${videoId}.`);
      return null;
    }

    // Join all segments into plain text
    const transcript = segments
      .map((s) => s.text)
      .join(" ")
      .replace(/\[Music\]/gi, "")
      .replace(/\[Applause\]/gi, "")
      .replace(/\s+/g, " ")
      .trim();

    if (transcript.length < 100) {
      console.warn(`Transcript for ${videoId} too short (${transcript.length} chars).`);
      return null;
    }

    // youtube-transcript fetches auto-generated captions by default;
    // treat all fetched transcripts as potentially auto-generated (conservative).
    const isAutoGenerated = true;

    console.log(
      `Transcript ready: ${transcript.length} characters (via YouTube API)`
    );
    return { transcript, isAutoGenerated };
  } catch (error: any) {
    const msg: string = error?.message ?? String(error);

    // Expected "no transcript" errors — not fatal
    if (
      msg.includes("No captions") ||
      msg.includes("disabled") ||
      msg.includes("Could not retrieve") ||
      msg.includes("unavailable")
    ) {
      console.warn(`No transcript available for ${videoId}: ${msg}`);
      return null;
    }

    // Any other error: log and fall through to audio path
    console.warn(
      `Transcript fetch failed for ${videoId}: ${msg} — will fall back to audio.`
    );
    return null;
  }
}
