/**
 * Fetch a YouTube video's caption/subtitle track via the YouTube transcript
 * API (no yt-dlp, no cookies, no bot-detection issues).
 *
 * Uses the `youtube-transcript` package which calls YouTube's public timedtext
 * endpoint directly — works from any IP including GitHub Actions and Cloud Run.
 *
 * Falls back to null if no transcript is available (e.g. auto-captions haven't
 * been generated yet for a very recent live stream). The caller (`getTranscript`)
 * then falls back to the full audio-download path.
 */

import { YoutubeTranscript, TranscriptResponse } from "youtube-transcript";

/**
 * Download the transcript for a YouTube video using the public timedtext API.
 * Returns the plain-text transcript, or null if unavailable.
 */
export async function fetchYouTubeCaptionsTranscript(
  videoId: string
): Promise<{ transcript: string; isAutoGenerated: boolean } | null> {
  // Validate videoId to prevent injection (YouTube IDs are always 11 alphanumeric/-/_ chars)
  if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    console.error(`Invalid videoId format: ${videoId}`);
    return null;
  }

  try {
    console.log(`Fetching transcript for ${videoId} via YouTube API...`);
    // Try each common English locale in order — some videos publish captions as
    // en-US, en-GB, or en-orig rather than plain "en".
    // YouTube ASR (auto-generated) tracks are always published as bare "en";
    // regional codes (en-US, en-GB, en-orig) indicate manually uploaded captions.
    const langCandidates = ["en", "en-US", "en-GB", "en-orig"];
    let segments: TranscriptResponse[] = [];
    let matchedLang: string | null = null;
    let lastError: any;
    for (const lang of langCandidates) {
      try {
        segments = await YoutubeTranscript.fetchTranscript(videoId, { lang });
        if (segments && segments.length > 0) { matchedLang = lang; break; }
      } catch (e) {
        lastError = e;
      }
    }
    if (segments.length === 0 && lastError) throw lastError;

    if (!segments || segments.length === 0) {
      console.warn(`No transcript segments returned for ${videoId}.`);
      return null;
    }

    // Join all segments into plain text
    const transcript = segments
      .map((s) => s.text)
      .join(" ")
      .replace(/\[Music\]/gi, "")
      .replace(/\[Applause\]/gi, "")
      .replace(/\s+/g, " ")
      .trim();

    if (transcript.length < 100) {
      console.warn(`Transcript for ${videoId} too short (${transcript.length} chars).`);
      return null;
    }

    // YouTube ASR (auto-generated) tracks are always bare "en"; regional codes
    // like en-US, en-GB, en-orig indicate manually uploaded captions.
    const isAutoGenerated = matchedLang === "en";

    console.log(
      `Transcript ready: ${transcript.length} characters (via YouTube API)`
    );
    return { transcript, isAutoGenerated };
  } catch (error: any) {
    const msg: string = error?.message ?? String(error);

    // Expected "no transcript available" — not a real error, caller falls back to audio
    if (
      msg.includes("No captions") ||
      msg.includes("disabled") ||
      msg.includes("Could not retrieve") ||
      msg.includes("unavailable")
    ) {
      console.warn(`No transcript available for ${videoId}: ${msg}`);
      return null;
    }

    // Unexpected error (network failure, parse error, etc.) — re-throw so the
    // caller can distinguish a real outage from "captions not ready yet".
    throw new Error(`Transcript fetch failed for ${videoId}: ${msg}`);
  }
}
