/**
 * Fetch a YouTube video's caption/subtitle track using yt-dlp in
 * subtitle-only mode (`--skip-download`).
 *
 * This downloads only the tiny subtitle JSON file (a few hundred KB) rather
 * than the full audio track (hundreds of MB), making it ~100x faster and
 * eliminating the GROQ Whisper transcription step entirely.
 *
 * yt-dlp handles all YouTube auth complexity (PO tokens, cookies, etc.) the
 * same way it does for audio — so this works anywhere yt-dlp works, including
 * on Cloud Run with the bgutil PO token sidecar.
 *
 * Falls back to null if no subtitle track is available (e.g. auto-captions
 * haven't been generated yet for a very recent live stream). The caller
 * (`getTranscript`) then falls back to the full audio-download path.
 */

import { exec } from "child_process";
import { promisify } from "util";
import { readFile, unlink } from "fs/promises";
import { tmpdir } from "os";
import { join } from "path";
import { getYtDlpCookieArgs } from "./processing";

const execAsync = promisify(exec);

interface TimedTextEvent {
  segs?: Array<{ utf8?: string }>;
}

interface TimedTextJson3 {
  events?: TimedTextEvent[];
}

function json3ToText(data: TimedTextJson3): string {
  const parts: string[] = [];
  for (const event of data.events || []) {
    if (!event.segs) continue;
    for (const seg of event.segs) {
      if (seg.utf8) parts.push(seg.utf8);
    }
    parts.push(" ");
  }
  return parts
    .join("")
    .replace(/\s+/g, " ")
    .replace(/\[Music\]/gi, "")
    .replace(/\[Applause\]/gi, "")
    .trim();
}

/**
 * Download only the auto-generated subtitle file for a YouTube video.
 * Returns the plain-text transcript, or null if unavailable.
 */
export async function fetchYouTubeCaptionsTranscript(
  videoId: string
): Promise<{ transcript: string; isAutoGenerated: boolean } | null> {
  const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const timestamp = Date.now();
  const outTemplate = join(tmpdir(), `subs-${videoId}-${timestamp}`);
  // yt-dlp appends .<lang>.json3 to the template
  const expectedFile = `${outTemplate}.en.json3`;
  const expectedFileOrig = `${outTemplate}.en-orig.json3`;

  const { args: cookieArgs, cleanup } = await getYtDlpCookieArgs();

  try {
    console.log(`Downloading subtitles for ${videoId} (no audio)...`);
    await execAsync(
      `yt-dlp --write-auto-sub --sub-lang "en.*" --skip-download --sub-format json3 ` +
        `-o "${outTemplate}.%(ext)s" --no-warnings --no-progress ` +
        `${cookieArgs} "${videoUrl}"`,
      { maxBuffer: 10 * 1024 * 1024 }
    );

    // Pick whichever file was written (en-orig or en)
    let subFile: string | null = null;
    for (const candidate of [expectedFile, expectedFileOrig]) {
      try {
        await readFile(candidate); // just check it exists
        subFile = candidate;
        break;
      } catch {
        // not this one
      }
    }

    // Also try glob for any other language variant written
    if (!subFile) {
      // yt-dlp may have written e.g. .en-US.json3
      const { stdout } = await execAsync(
        `ls "${outTemplate}"*.json3 2>/dev/null || true`
      );
      const files = stdout.trim().split("\n").filter(Boolean);
      if (files.length > 0) subFile = files[0];
    }

    if (!subFile) {
      console.warn(`No subtitle file written for ${videoId}.`);
      return null;
    }

    const raw = await readFile(subFile, "utf-8");
    const data = JSON.parse(raw) as TimedTextJson3;
    const transcript = json3ToText(data);

    if (!transcript || transcript.length < 100) {
      console.warn(
        `Subtitle file for ${videoId} too short (${transcript.length} chars).`
      );
      return null;
    }

    console.log(
      `Subtitle transcript ready: ${transcript.length} characters (auto-generated via yt-dlp)`
    );
    return { transcript, isAutoGenerated: true };
  } catch (error: any) {
    // yt-dlp exits non-zero when no subtitles exist — that's expected, not fatal.
    if (
      error.message?.includes("no subtitles") ||
      error.message?.includes("no automatic captions") ||
      error.message?.includes("No automatic captions")
    ) {
      console.warn(`No auto-captions available for ${videoId}.`);
      return null;
    }
    // Any other error: log and fall through to audio path
    console.warn(
      `Subtitle download failed for ${videoId}: ${error.message} — will fall back to audio.`
    );
    return null;
  } finally {
    await cleanup();
    // Clean up any subtitle files written
    for (const candidate of [expectedFile, expectedFileOrig]) {
      try { await unlink(candidate); } catch { /* ignore */ }
    }
    // Clean up any other variant files
    try {
      const { stdout } = await execAsync(
        `ls "${outTemplate}"*.json3 2>/dev/null || true`
      );
      for (const f of stdout.trim().split("\n").filter(Boolean)) {
        try { await unlink(f); } catch { /* ignore */ }
      }
    } catch { /* ignore */ }
  }
}

