/**
 * Fetch a town hall transcript through the official YouTube Data API, signed in
 * as the channel owner.
 *
 * Why this exists
 * ---------------
 * Every previous transcript path tried to read captions the way an anonymous
 * viewer would, and YouTube has spent two years making that harder:
 *
 *   - `youtube-transcript` (see captions.ts) hits the public `timedtext`
 *     endpoint. YouTube now blocks that from datacenter ranges, so it fails
 *     from Cloud Run while working fine from a laptop.
 *   - yt-dlp with a `--cookies` file works until the cookies go stale, which
 *     is days. Re-exporting them by hand every week is the thing that has not
 *     been sustainable.
 *   - yt-dlp with PO tokens (the bgutil sidecar) does not help on its own,
 *     because the player request is refused before PO tokens are consulted.
 *
 * All three are workarounds for not being logged in. But MoonDAO *owns* these
 * videos, and the Data API will hand a channel's own caption tracks — including
 * the auto-generated ASR track — straight to the owner via `captions.download`.
 * No cookies, no PO tokens, no bot detection, no IP reputation.
 *
 * The credential is an OAuth refresh token, which is not a browser cookie and
 * does not expire on the same timescale.
 *
 * !! The one thing that will bite you !!
 * --------------------------------------
 * If the Google Cloud OAuth consent screen is left in **Testing** publishing
 * status, Google expires refresh tokens after **7 days**, and every call here
 * starts failing with `invalid_grant`. That is almost certainly what "the key
 * expires really fast" has been. Set the consent screen to **In production**
 * (see README) and the refresh token stops expiring. `captions:check` calls
 * this out explicitly when it sees `invalid_grant`.
 */

export type OwnerCaptionsResult = {
  transcript: string
  isAutoGenerated: boolean
  trackKind: string
  language: string
}

export type CaptionTrack = {
  id: string
  language: string
  trackKind: string
  name: string
  isDraft: boolean
}

/** Raised with a human-readable cause so the caller can log something useful. */
export class OwnerCaptionsError extends Error {
  readonly hint?: string
  constructor(message: string, hint?: string) {
    super(message)
    this.name = 'OwnerCaptionsError'
    this.hint = hint
  }
}

export type OAuthConfig = {
  clientId: string
  clientSecret: string
  refreshToken: string
}

/**
 * Reads the OAuth credentials from the environment. Returns null (rather than
 * throwing) when they are absent, so `getTranscript` can quietly fall through
 * to the older paths on a deployment that has not been configured yet.
 */
export function getOAuthConfig(): OAuthConfig | null {
  const clientId = process.env.YOUTUBE_OAUTH_CLIENT_ID
  const clientSecret = process.env.YOUTUBE_OAUTH_CLIENT_SECRET
  const refreshToken = process.env.YOUTUBE_OAUTH_REFRESH_TOKEN

  if (!clientId || !clientSecret || !refreshToken) return null
  return { clientId, clientSecret, refreshToken }
}

/** Exchanges the long-lived refresh token for a short-lived access token. */
export async function getAccessToken(config: OAuthConfig): Promise<string> {
  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      client_id: config.clientId,
      client_secret: config.clientSecret,
      refresh_token: config.refreshToken,
      grant_type: 'refresh_token',
    }),
  })

  const body = (await response.json().catch(() => ({}))) as {
    access_token?: string
    error?: string
    error_description?: string
  }

  if (!response.ok || !body.access_token) {
    const error = body.error ?? `HTTP ${response.status}`

    if (error === 'invalid_grant') {
      throw new OwnerCaptionsError(
        `Refresh token rejected (invalid_grant): ${body.error_description ?? ''}`.trim(),
        'The refresh token has been revoked or has expired. The usual cause is an ' +
          'OAuth consent screen still in "Testing" status, which expires refresh ' +
          'tokens after 7 days — set it to "In production" in Google Cloud Console, ' +
          'then mint a new token with `yarn oauth:setup`.'
      )
    }

    throw new OwnerCaptionsError(
      `Token exchange failed: ${error}${
        body.error_description ? ` — ${body.error_description}` : ''
      }`
    )
  }

  return body.access_token
}

/** Lists the caption tracks YouTube holds for a video the token can see. */
export async function listCaptionTracks(
  videoId: string,
  accessToken: string
): Promise<CaptionTrack[]> {
  const url = `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${encodeURIComponent(
    videoId
  )}`

  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${accessToken}` },
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    if (response.status === 403) {
      throw new OwnerCaptionsError(
        `captions.list returned 403 for ${videoId}: ${text.slice(0, 300)}`,
        'The authorised account does not own this video. Confirm the OAuth token ' +
          'was minted from the Google account that owns the @officialmoondao channel, ' +
          'not a personal account with mere access to it.'
      )
    }
    throw new OwnerCaptionsError(
      `captions.list failed for ${videoId}: HTTP ${response.status} ${text.slice(0, 300)}`
    )
  }

  const data = (await response.json()) as {
    items?: Array<{
      id?: string
      snippet?: {
        language?: string
        trackKind?: string
        name?: string
        isDraft?: boolean
      }
    }>
  }

  return (data.items ?? [])
    .filter((item) => item.id)
    .map((item) => ({
      id: item.id as string,
      language: item.snippet?.language ?? '',
      trackKind: item.snippet?.trackKind ?? '',
      name: item.snippet?.name ?? '',
      isDraft: item.snippet?.isDraft ?? false,
    }))
}

/**
 * Picks the best track: a finished human-written English one if it exists,
 * otherwise the auto-generated (ASR) one, which is what a live stream will
 * have a few hours after it ends.
 */
export function selectBestTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  const english = tracks.filter(
    (t) => !t.isDraft && (t.language === 'en' || t.language.startsWith('en-'))
  )
  const pool = english.length > 0 ? english : tracks.filter((t) => !t.isDraft)
  if (pool.length === 0) return null

  const manual = pool.find((t) => t.trackKind !== 'ASR')
  return manual ?? pool[0]
}

/** Downloads one track as SRT. */
export async function downloadCaptionTrack(
  trackId: string,
  accessToken: string
): Promise<string> {
  const url = `https://www.googleapis.com/youtube/v3/captions/${encodeURIComponent(
    trackId
  )}?tfmt=srt`

  const response = await fetch(url, {
    headers: { Authorization: `Bearer ${accessToken}` },
  })

  if (!response.ok) {
    const text = await response.text().catch(() => '')
    if (response.status === 403) {
      throw new OwnerCaptionsError(
        `captions.download returned 403 for track ${trackId}: ${text.slice(0, 300)}`,
        'YouTube refuses owner downloads of third-party-contributed tracks, and ' +
          'has historically been inconsistent about ASR tracks. If the track kind ' +
          'is ASR and this keeps happening, the audio path is the remaining option.'
      )
    }
    throw new OwnerCaptionsError(
      `captions.download failed for track ${trackId}: HTTP ${response.status} ${text.slice(0, 300)}`
    )
  }

  return response.text()
}

/**
 * Flattens SRT into plain prose.
 *
 * ASR tracks are "rolling": each cue repeats the tail of the previous one so
 * the on-screen text scrolls. Joining cues naively triples the transcript and
 * wastes context window, so consecutive duplicate lines are dropped.
 */
export function srtToPlainText(srt: string): string {
  const lines = srt.split(/\r?\n/)
  const text: string[] = []

  for (const raw of lines) {
    const line = raw.trim()
    if (!line) continue
    if (/^\d+$/.test(line)) continue // cue index
    if (line.includes('-->')) continue // timing
    text.push(line)
  }

  const deduped: string[] = []
  for (const line of text) {
    if (deduped.length === 0 || deduped[deduped.length - 1] !== line) {
      deduped.push(line)
    }
  }

  return deduped
    .join(' ')
    .replace(/<[^>]+>/g, '')
    .replace(/\[Music\]/gi, '')
    .replace(/\[Applause\]/gi, '')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * The whole path end to end. Returns null when the video simply has no caption
 * track yet (a stream that ended an hour ago), and throws when something is
 * actually wrong, so the caller can tell "not ready" from "broken".
 */
export async function fetchOwnerCaptionsTranscript(
  videoId: string
): Promise<OwnerCaptionsResult | null> {
  if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    throw new OwnerCaptionsError(`Invalid videoId format: ${videoId}`)
  }

  const config = getOAuthConfig()
  if (!config) {
    throw new OwnerCaptionsError(
      'YouTube OAuth is not configured',
      'Set YOUTUBE_OAUTH_CLIENT_ID, YOUTUBE_OAUTH_CLIENT_SECRET and ' +
        'YOUTUBE_OAUTH_REFRESH_TOKEN. Run `yarn oauth:setup` to mint the last one.'
    )
  }

  const accessToken = await getAccessToken(config)
  const tracks = await listCaptionTracks(videoId, accessToken)

  if (tracks.length === 0) {
    console.warn(
      `No caption tracks listed for ${videoId} yet (auto-captions usually appear a few hours after a stream ends).`
    )
    return null
  }

  const track = selectBestTrack(tracks)
  if (!track) {
    console.warn(`Only draft caption tracks exist for ${videoId}.`)
    return null
  }

  console.log(
    `Downloading ${track.trackKind || 'unknown'} caption track (${
      track.language || 'unknown language'
    }) for ${videoId} as channel owner...`
  )

  const srt = await downloadCaptionTrack(track.id, accessToken)
  const transcript = srtToPlainText(srt)

  if (transcript.length < 100) {
    console.warn(
      `Owner caption track for ${videoId} produced only ${transcript.length} characters; treating as unusable.`
    )
    return null
  }

  console.log(`Transcript ready: ${transcript.length} characters (via owner API)`)

  return {
    transcript,
    isAutoGenerated: track.trackKind === 'ASR',
    trackKind: track.trackKind,
    language: track.language,
  }
}
