name: test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Local Chain with Anvil
        run: |
          anvil --fork-url https://1.rpc.thirdweb.com/${{ secrets.THIRDWEB_CLIENT_ID }} &
        id: local-chain

      - name: Install npm dependencies
        run: |
          npm install --legacy-peer-deps
        id: install-dependencies

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --via-ir --optimize --optimizer-runs 200
        id: build

      - name: Run Forge tests
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          forge test --via-ir --optimize --optimizer-runs 200 --fork-url http://localhost:8545 -vvvv
        id: test
