namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_ANNOUNCEMENTS_API_URL: string
    DISCORD_CLIENT_ID: string
    DISCORD_CLIENT_SECRET: string
    DISCORD_BOT_TOKEN: string
    NEXT_PUBLIC_VMOONEY_REQUIRED_STAKE: number
    NEXT_PUBLIC_CHAIN: string
    NEXT_PUBLIC_GOOGLE_SHEETS_EMAIL: string
    NEXT_PUBLIC_GOOGLE_SHEETS_SECRET: string
    NEXT_PUBLIC_GOOGLE_SPREADSHEET_ID: string
    NEXT_PUBLIC_INFURA_URL: string
    TWITTER_CLIENT_ID: string
    TWITTER_CLIENT_SECRET: string
    OPENAI_API_KEY: string
    SHOPIFY_ACCESS_TOKEN: string
    FIREBASE_API_KEY: string
    FIREBASE_AUTH_DOMAIN: string
    FIREBASE_PROJECT_ID: string
    FIREBASE_MSG_SENDER_ID: string
    FIREBASE_APP_ID: string
  }
}
