namespace NodeJS {
  interface ProcessEnv {
    DISCORD_CLIENT_ID: string
    DISCORD_CLIENT_SECRET: string
    NEXT_PUBLIC_GOOGLE_SHEETS_EMAIL: string
    NEXT_PUBLIC_GOOGLE_SHEETS_SECRET: string
    NEXT_PUBLIC_GOOGLE_SPREADSHEET_ID: string
    TWITTER_CLIENT_ID: string
    TWITTER_CLIENT_SECRET: string
    OPENAI_API_KEY: string
    SHOPIFY_ACCESS_TOKEN: any
    FIREBASE_API_KEY: string
    FIREBASE_AUTH_DOMAIN: string
    FIREBASE_PROJECT_ID: string
    FIREBASE_STORAGE_BUCKET: any
    FIREBASE_MSG_SENDER_ID: string
    FIREBASE_APP_ID: string
  }
}
