namespace NodeJS {
  interface ProcessEnv {
    DISCORD_CLIENT_ID: string
    DISCORD_CLIENT_SECRET: string
    NEXT_PUBLIC_GOOGLE_SHEETS_EMAIL: string
    NEXT_PUBLIC_GOOGLE_SHEETS_SECRET: string
    NEXT_PUBLIC_GOOGLE_SPREADSHEET_ID: string
    TWITTER_CLIENT_ID: string
    TWITTER_CLIENT_SECRET: string
  }
}
