[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@hpke/**", "node_modules/@privy-io/**"]
