module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      screens: {
        '3xl': '1920px',
        '4xl': '2560px',
      },
      fontFamily: {
        display: ['"Bebas Neue"', 'sans-serif'],
        body: ['Rajdhani', '"Helvetica Neue"', 'sans-serif'],
        GoodTimes: ['"Bebas Neue"', 'Good Times', 'sans-serif'],
        RobotoMono: ['Roboto Mono', 'monospace'],
        Montserrat: ['Montserrat', 'sans-serif'],
        retro: ['"Share Tech Mono"', '"Roboto Mono"', 'monospace'],
        eva: ['"Bebas Neue"', 'sans-serif'],
      },
      animation: {
        fadeIn: 'fadeIn 0.5s ease-in',
        fadeInTo75: 'fadeIn 0.5s ease-in',
        fadeInSlow: 'fadeIn 1s ease-in',
        fadeInSlowTo75: 'fadeInTo75 1s ease-in',
        notification: 'notification 5s',
        highlight: 'highlight 3s ease-out',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'scanline-move': 'scanlineMove 8s linear infinite',
        'flicker': 'flicker 0.15s infinite',
        'hud-blink': 'hudBlink 4s ease-in-out infinite',
        'hud-blink-slow': 'hudBlink 6s ease-in-out infinite',
        'border-glow': 'borderGlow 5s ease-in-out infinite',
        'data-scroll': 'dataScroll 20s linear infinite',
        'bar-fill': 'barFill 8s ease-in-out infinite',
        'sweep': 'sweep 4s ease-in-out infinite',
      },
      colors: {
        'title-light': '#172554',
        'title-dark': '#00ffc8',
        'light-text': '#071732',
        'dark-text': '#e0fff0',
        faded: '#3a7a6a',
        'moon-gold': '#ff9f1c',
        'moon-blue': '#00e5ff',
        'moon-indigo': '#7b2fff',
        'moon-green': '#39ff14',
        'moon-orange': '#ff6b35',
        'detail-light': '#60a5fa',
        'detail-dark': '#00ffc8',
        'stronger-light': '#1d4ed8',
        'stronger-dark': '#ff9f1c',
        'background-light': '#0a0a0a',
        'background-dark': '#050505',
        'dark-highlight': '#00ffc8',
        'light-highlight': '#ff2a6d',

        'darkest-cool': '#020208',
        'dark-cool': '#0a0a12',
        'mid-cool': '#0d1a2a',
        'mid-cool-2': '#0a1220',
        cool: '#0d1a30',
        'light-cool': '#00e5ff',
        'dark-warm': '#1a0a12',
        'light-warm': '#ff2a6d',

        n3blue: '#00e5ff',
        n3green: '#39ff14',
        'n3blue-100': '#ccffff',
        'n3green-100': '#ccffcc',
        n3bg: '#0a0a0a',
        n3nav: '#00aa88',
        moonBlue: '#00aaff',
        'moon-orange': '#ff6b35',

        'retro-cyan': '#00ffc8',
        'retro-magenta': '#ff2a6d',
        'retro-amber': '#ff9f1c',
        'retro-green': '#39ff14',
        'retro-blue': '#00e5ff',
        'retro-purple': '#7b2fff',
        'retro-pink': '#ff00aa',
        'retro-grid': '#1a3a2a',
      },
      keyframes: {
        notification: {
          '0%': { left: '350px', opacity: 1 },
          '15%': { left: '-15px', opacity: 1 },
          '80%': { left: '-10px', opacity: 1 },
          '100%': { left: '350px', opacity: 0 },
        },
        fadeIn: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        fadeInTo75: {
          '0%': { opacity: 0 },
          '100%': { opacity: 0.75 },
        },
        highlight: {
          '0%': { color: 'white' },
          '50%': { color: '#00ffc8' },
          '100%': { color: 'white' },
        },
        glowPulse: {
          '0%, 100%': { opacity: 0.6 },
          '50%': { opacity: 1 },
        },
        scanlineMove: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        flicker: {
          '0%': { opacity: 0.97 },
          '50%': { opacity: 1 },
          '100%': { opacity: 0.98 },
        },
        hudBlink: {
          '0%, 100%': { opacity: 0.4 },
          '50%': { opacity: 1 },
        },
        borderGlow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0, 255, 200, 0.1), inset 0 0 5px rgba(0, 255, 200, 0.02)' },
          '50%': { boxShadow: '0 0 15px rgba(0, 255, 200, 0.25), inset 0 0 10px rgba(0, 255, 200, 0.05)' },
        },
        dataScroll: {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        barFill: {
          '0%, 100%': { width: '35%' },
          '25%': { width: '72%' },
          '50%': { width: '58%' },
          '75%': { width: '85%' },
        },
        sweep: {
          '0%': { transform: 'translateX(-100%)' },
          '50%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
      boxShadow: {
        'retro-cyan': '0 0 10px rgba(0, 255, 200, 0.3), 0 0 20px rgba(0, 255, 200, 0.1)',
        'retro-magenta': '0 0 10px rgba(255, 42, 109, 0.3), 0 0 20px rgba(255, 42, 109, 0.1)',
        'retro-amber': '0 0 10px rgba(255, 159, 28, 0.3), 0 0 20px rgba(255, 159, 28, 0.1)',
        'retro-glow': '0 0 15px rgba(0, 255, 200, 0.2), inset 0 0 15px rgba(0, 255, 200, 0.05)',
      },
    },
  },
  darkMode: 'class',
  plugins: [
    require('daisyui'),
    require('tailwind-scrollbar-hide'),
    require('@tailwindcss/typography'),
  ],
  daisyui: {
    themes: [
      {
        mytheme: {
          primary: '#00ffc8',
          secondary: '#ff2a6d',
          accent: '#7b2fff',
          neutral: '#1a1a2e',
          error: '#ff2a6d',
          'primary-content': '#000000',
          'base-100': '#0a0a0a',
          'base-content': '#00ffc8',
          moon: '#ff6b35',
        },
      },
    ],
  },
}
