name: XPContracts

on:
  push:
    paths:
      - "xp/**"
      - ".github/workflows/xp.yml"
  pull_request:
    paths:
      - "xp/**"
      - ".github/workflows/xp.yml"
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge build
        run: |
          forge build --via-ir --sizes
        working-directory: xp
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv --via-ir
        working-directory: xp
        id: test
